### ISSUE TITLE
where is the data.tsv file?

### ISSUE THREAD

**Issue by zhaogxd** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#12]
Could you please tell me where to get the data.tsv file for the demo of the course?

**Comment by zhaogxd** [comment]
Please ignore my question. I was able to generate the data.tsv file successfully by running the LogProducer.scala program.

**Comment by aalkilani** [comment]
@zhaogxd , thanks for the update. I will go ahead and close this.
