### ISSUE TITLE
Applying the Lambda Architecture with Spark, Kafka, and Cassandra 

### ISSUE THREAD

**Issue by vsmeruga** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#14]
[cygwin_error_cmd.docx](https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/files/710289/cygwin_error_cmd.docx)
In this video, author is : Ahmad Alkilani. asked to execute command for cloning repository.

 >git clone https://github.com/aalkilani/spark-kafta-cassandra-applying-lambda-architecture.git

 Error came as below after entering my email address & password: 

 Cloning into 'spark-kafta-cassandra-applying-lambda-architecture'...
 remote: Repository not found.
 fatal: repository 'https://github.com/aalkilani/spark-kafta-cassandra-applying-lambda-architecture.git/' not found

 Please help on this ASAP. Attached error screenshot.

**Comment by aalkilani** [comment]
Could it be the extra "/" at the end of the got clone that's causing this? The last 4 characters for the clone command should be ".git" no slash.

**Comment by vsmeruga** [comment]
I believe I haven't provided extra / at the end of the command. Will try in the evening and confirm. Thanks

**Comment by vsmeruga** [comment]
I attached screenshot for the same. I am not able to open my screenshot file from office here.

**Comment by aalkilani** [comment]
@vsmeruga has this worked for you? I haven't seen an update on this or a screenshot attached here so  I'm assuming you managed to get this working? Mind sharing your experience here and how you resolved this?

**Comment by vsmeruga** [comment]
Hi Ahmed
Looks like I am successful in this step:

 But next step, failed: vagrant up. Please advise.. 


Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Thursday, February 2, 2017 12:15 AM, Ahmad Alkilani <notifications@github.com> wrote:
 

 @vsmeruga has this worked for you? I haven't seen an update on this or a screenshot attached here so I'm assuming you managed to get this working? Mind sharing your experience here and how you resolved this?—

**Comment by aalkilani** [comment]
When you run vagrant up, are you inside of the vagrant folder or are you still outside in the root directory of the project?

**Comment by vsmeruga** [comment]
Hi Ahmad
Please see the path below :$ pwd
/cygdrive/c/Boxes/spark-kafka-cassandra-applying-lambda-architecture/vagrant Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Saturday, February 4, 2017 9:13 AM, Ahmad Alkilani <notifications@github.com> wrote:
 

 When you run vagrant up, are you inside of the vagrant folder or are you still outside in the root directory of the project?—

**Comment by vsmeruga** [comment]
Hi Ahmed
Please help. "vagrant up" - not working

 Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Saturday, February 4, 2017 10:00 AM, vijay meruga <vsmeruga@yahoo.com> wrote:
 

 Hi Ahmad
Please see the path below :$ pwd
/cygdrive/c/Boxes/spark-kafka-cassandra-applying-lambda-architecture/vagrant Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Saturday, February 4, 2017 9:13 AM, Ahmad Alkilani <notifications@github.com> wrote:
 

 When you run vagrant up, are you inside of the vagrant folder or are you still outside in the root directory of the project?—

**Comment by vsmeruga** [comment]
Hi Ahmed
Do I need to set any ENV path variable for Cygwin which was not mentioned in the video? Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Sunday, February 26, 2017 8:53 AM, vijay meruga <vsmeruga@yahoo.com> wrote:
 

 Hi Ahmed
Please help. "vagrant up" - not working

 Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Saturday, February 4, 2017 10:00 AM, vijay meruga <vsmeruga@yahoo.com> wrote:
 

 Hi Ahmad
Please see the path below :$ pwd
/cygdrive/c/Boxes/spark-kafka-cassandra-applying-lambda-architecture/vagrant Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Saturday, February 4, 2017 9:13 AM, Ahmad Alkilani <notifications@github.com> wrote:
 

 When you run vagrant up, are you inside of the vagrant folder or are you still outside in the root directory of the project?—

**Comment by vsmeruga** [comment]
This path exists already under path : C:\ProgramData\chocolatey\bin;
 Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Sunday, February 26, 2017 9:23 AM, vijay meruga <vsmeruga@yahoo.com> wrote:
 

 Hi Ahmed
Do I need to set any ENV path variable for Cygwin which was not mentioned in the video? Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Sunday, February 26, 2017 8:53 AM, vijay meruga <vsmeruga@yahoo.com> wrote:
 

 Hi Ahmed
Please help. "vagrant up" - not working

 Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Saturday, February 4, 2017 10:00 AM, vijay meruga <vsmeruga@yahoo.com> wrote:
 

 Hi Ahmad
Please see the path below :$ pwd
/cygdrive/c/Boxes/spark-kafka-cassandra-applying-lambda-architecture/vagrant Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Saturday, February 4, 2017 9:13 AM, Ahmad Alkilani <notifications@github.com> wrote:
 

 When you run vagrant up, are you inside of the vagrant folder or are you still outside in the root directory of the project?—

**Comment by aalkilani** [comment]
@vsmeruga , are you still having problems or can we close this ticket?
If you're still having issues can you post the exact error you see so we can help troubleshoot. Thanks

**Comment by safiqksm** [comment]
Please help. "vagrant up" is not working. Inside of the vagrant folder.

**Comment by harneetsachdeva** [comment]
Hello Ahmed,

I am trying to bringup  vagrant box on version on  Virtual Box 5.0.40 windows 10 pro (since 5.0.10 doesn't run windows 10 pro) but getting error while executing vagrant up. it fails at bcrypt.dll. A known virtualbox issue. 
https://forums.virtualbox.org/viewtopic.php?f=38&t=83732
Kindly suggest what can be done.

Thanks and Regards,
Harneet
harneet.sachdeva@gmail.com
