### ISSUE TITLE
Vagrant UP error - Help #14 

### ISSUE THREAD

**Issue by vsmeruga** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#17]
Ahmad A,

I am struck at this point from long time. I did sent you email and waiting for response on it.

Please help me on this issue ASAP. Attached screen shots.

Thanks
VJ
[vagrant up error.docx](https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/files/824052/vagrant.up.error.docx)

**Comment by marobabic** [comment]
Ahmad, you need to make sure you have vagrant installed and in your path. In your path means that your environment variable PATH contains directory into which you installed vagrant. You can find out what your path is by executing followowing in your cygwin:
`echo $PATH`
If you can't see vagrant directory there - which is most likely the reason of your problem - add the directory tho your path like this:
`export PATH=$PATH;/path/to/your/vagrant/dir`
After this you should be able to run vagrant like you expect.

**Comment by aalkilani** [comment]
@marobabic , thanks for the response on this. I believe I've also been able to get @vsmeruga going through Pluralsight customer support so closing this ticket. For everyone's reference, there's a troubleshooting guide here: https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/blob/master/vagrant/troubleshooting.md

This is especially useful if you're on Windows. I do take pull requests if anyone has input on making the guide better.

Thanks!

**Comment by vsmeruga** [comment]
Hi 
I am trying this from the link you sent to me.

On Windows
This might require an additional step depending on where you installed Vagrant: From cygwin on the host machine (outside of the VM) setup Vagrant's home directory to something without spaces. For example to setup Vagrant's home directory to my "F:" drive on Windows under a "Boxes" folder, in Windows this would be "F:\Boxes"export VAGRANT_HOME=/cygdrive/f/Boxes
For all operating systems (including Windows)
Install the vagrant-vbguest plugin: From cygwin on the host machine (outside of the VM) install the vagrant-vbguest pluginvagrant plugin install vagrant-vbguest
Above export command is successful. VAGRANT_HOME path is set. Tried to install vbguest plugin and not successful. Please suggest ASAP.


 
Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 

    On Friday, March 24, 2017 3:58 PM, Ahmad Alkilani <notifications@github.com> wrote:
 

 @marobabic , thanks for the response on this. I believe I've also been able to get @vsmeruga going through Pluralsight customer support so closing this ticket. For everyone's reference, there's a troubleshooting guide here: https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/blob/master/vagrant/troubleshooting.mdThis is especially useful if you're on Windows. I do take pull requests if anyone has input on making the guide better.Thanks!—

**Comment by vsmeruga** [comment]
Hi 
Sorry to say this. Issue is not resolved. Please do not close the ticket.
I am trying this from the link you sent to me.

On Windows
This might require an additional step depending on where you installed Vagrant: From cygwin on the host machine (outside of the VM) setup Vagrant's home directory to something without spaces. For example to setup Vagrant's home directory to my "F:" drive on Windows under a "Boxes" folder, in Windows this would be "F:\Boxes"export VAGRANT_HOME=/cygdrive/f/Boxes
For all operating systems (including Windows)
Install the vagrant-vbguest plugin: From cygwin on the host machine (outside of the VM) install the vagrant-vbguest pluginvagrant plugin install vagrant-vbguest
Above export command is successful. VAGRANT_HOME path is set. Tried to install vbguest plugin and not successful. Please suggest ASAP.


 
Thanks & Regards,Vijay Sekhar Meruga0752-381-9470 
 

    On Friday, March 24, 2017 3:58 PM, Ahmad Alkilani <notifications@github.com> wrote:
 

 @marobabic , thanks for the response on this. I believe I've also been able to get @vsmeruga going through Pluralsight customer support so closing this ticket. For everyone's reference, there's a troubleshooting guide here: https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/blob/master/vagrant/troubleshooting.mdThis is especially useful if you're on Windows. I do take pull requests if anyone has input on making the guide better.Thanks!—
