### ISSUE TITLE
Make sure you port forward port 8988 to the guest

### ISSUE THREAD

**Issue by notlikethis1** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#18]
If you are following 

https://app.pluralsight.com/player?course=spark-kafka-cassandra-applying-lambda-architecture&author=ahmad-alkilani&name=spark-kafka-cassandra-applying-lambda-architecture-m1&clip=4&mode=live

Make sure that you config you vagrant file to include:
Vagrant.configure("2") do |config|
    #include this
    config.vm.network "forwarded_port", guest: 8988, host: 8988
end

also after rebooting make sure all the processes are running:
>docker ps -a
and if they show exited start them again:
>docker ps start zeppelin 
repeat for all the docker containers.

**Comment by aalkilani** [comment]
@Stayin1 , that port is already set as part of the vagrant file. It's possible a host process was already using the port when you tried to bring the VM up the first time around but the port is already configured as you can see here: https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/blob/master/vagrant/Vagrantfile#L32

Also, if you want a simple way to ensure everything is up to date any fixes released after you've downloaded the vagrant box are applied. Simply
`git pull origin master`
`vagrant reload --provision`

Thanks for the input.
