### ISSUE TITLE
Vagrant up throws error

### ISSUE THREAD

**Issue by amirtoole** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#2]
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'aalkilani/spark-kafka-cassandra-applying-lambda-architecture' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'aalkilani/spark-kafka-cassandra-applying-lambda-architecture' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture"]
Error:
```

Environment:
OS X 10.12.1
$ vagrant --version
Vagrant 1.8.7

**Comment by aalkilani** [comment]
This is a problem with vagrant on OS X as documented here: https://github.com/mitchellh/vagrant/issues/7970

See this stackoverflow discussion for a workaround:
http://stackoverflow.com/questions/40473943/vagrant-box-could-not-be-found-or-could-not-be-accessed-in-the-remote-catalog

Also now noted in troubleshooting section:
https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/blob/master/vagrant/troubleshooting.md
