### ISSUE TITLE
stdin is not tty

### ISSUE THREAD

**Issue by causevic** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#9]
There's an error message on Mac in ```vagrant up``` output, see below. 
Machine boots, I can ssh to it, but the error appears each and every time.

```
==> default: Checking if box 'aalkilani/spark-kafka-cassandra-applying-lambda-architecture' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: docker-images (shell)...
    default: Running: inline script
**==> default: stdin: is not a tty**
==> default: zookeeper
==> default: spark-1.6.3
==> default: cassandra
==> default: zeppelin
==> default: kafka

```

**Comment by aalkilani** [comment]
Thanks for reporting. This doesn't cause any problems and can safely be ignored however it has now been addressed. Get latest from git repository and you should be good to go.
`git clone origin master`
`vagrant provision`

Next time you `vagrant reload` or `vagrant up` you shouldn't see this message.
